[project]
name = "comprehensive-rust-authenticator"
authors = ["Anonymous Developer"]
description = "A comprehensive Rust-based authentication and affiliate management system on Stacks blockchain"
telemetry = false
requirements = []
[contracts.auth-manager]
path = "contracts/auth-manager.clar"
depends_on = []

[contracts.user-leaderboard]
path = "contracts/user-leaderboard.clar"
depends_on = []

[contracts.reward-distributor]
path = "contracts/reward-distributor.clar"
depends_on = []

[contracts.platform-registry]
path = "contracts/platform-registry.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
